### ISSUE TITLE
Merge to logict?

### ISSUE THREAD

**Issue by Bodigrim** [Borgvall/logict#2]
Hi there, I am a new maintainer of `logict`. I found your patches at http://hub.darcs.net/dolio/logict/issue/4. Could you possibly prepare a PR to `logict`'s new home at https://github.com/Bodigrim/logict?

**Comment by Borgvall** [comment]
Hi Bodigirim,

It has been quite a while, since I have worked on this repo and it has low priority for me now. However some commits are still useful, and can be cherry picked. Other commits I would do differently these days, or just drop them.

So I will not prepare a pull request, but feel free to cherry pick commits yourself.

Best regards
Johannes Röhl


Am 19.06.19, 15:44, Bodigrim <notifications@github.com> schrieb:
Hi there, I am a new maintainer of logict. I found your patches at http://hub.darcs.net/dolio/logict/issue/4. Could you possibly prepare a PR to logict's new home at https://github.com/Bodigrim/logict?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Borgvall/logict/issues/2?email_source=notifications\u0026email_token=AALB6K35MQ2K6NPIYWNFEADP3IZ3DA5CNFSM4HZJY4PKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G2M377A",
"url": "https://github.com/Borgvall/logict/issues/2?email_source=notifications\u0026email_token=AALB6K35MQ2K6NPIYWNFEADP3IZ3DA5CNFSM4HZJY4PKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G2M377A",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Bodigrim** [comment]
Thanks!
